/**/controller_manager:
  ros__parameters:
    update_rate: 500

    force_torque_sensor_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

/**/force_torque_sensor_broadcaster:
  ros__parameters:
    sensor_name: $(var tf_prefix)ft_sensor
    frame_id: $(var tf_prefix)ft_sensor_link
    state_interface_names:
      - force.x
      - force.y
      - force.z
      - torque.x
      - torque.y
      - torque.z
    sensor_filter_chain:
      filter1:
        name: fts_lowpass_filter
        type: control_filters/LowPassFilterWrench 
        params:
          sampling_frequency: 500.0 
          damping_frequency: 5.0 
          damping_intensity: 0.0
